### ISSUE TITLE
The speed is so slow

### ISSUE THREAD

**Issue by ILG2021** [supershaneski/openai-whisper-api#1]
I have tried your nice project. But I find it cost a very long to get the result. I have used Azure speech recognizer, it is about 4-5 to get the result. But I think whisper cost about 10 seconds. It is very hard to use it in the production.

**Comment by supershaneski** [comment]
Sorry for taking time to reply.

I have no access to Azure so I cannot do comparison.

However, I made a test to check the speed so please see if you have the same result.

**Audio data**

[Damian Lewis as Antony in Julius Caesar via Guardian Culture](https://youtu.be/q89MLuLSJgk)
URL: https://youtu.be/q89MLuLSJgk
Duration: 02:33

**App settings**

Using whisper-api
MaxPause: 2500ms
MinDecibels: -60dB
Transcriptions
Language: English
Temperature: 0

Note that from the setting, it will wait for 2.5s before processing (sending to back end).

Because of the MaxPause setting, the transcription is divided into three files.
Audio data is saved as webm.

**Result**

1st part
File size: 693KB
Duration: 01:03
Process time: 4s

2nd part
File size: 808KB
Duration: 01:00
Process time: 4s

3rd part
File size: 462KB
Duration: 00:29
Process time: 2s

**Comment by ILG2021** [comment]
Thank you for your reply. I have transfered to fast-whisper which runs on local.
